environment:
  _PIP_ADDITIONAL_REQUIREMENTS: >-
    apache-airflow-providers-databricks==6.9.0
    databricks-sdk==0.28.0
    databricks-sql-connector==3.4.0
    yfinance==1.6.0
    pandas==2.2.2
    pyyaml==6.0.1
    python-dotenv==1.0.1

